actors = [
        "Mobile app",
        "Desktop application",
        "Program",
        "Wearable",
        "GUI",
        "API",
        "Device",
        "Robot",
        "Microcontroller",
        "Location-based social network",
        "Subscription model",
        "Digital assistant",
        "Consultancy",
        "Product"
        ]

actions = [
        "helps to find",
        "matches",
        "calculates",
        "scrapes",
        "simulates",
        "visualizes",
        "computes",
        "saves",
        "supports",
        "lists",
        "creates",
        "connects",
        "scales",
        "identifies",
        "finds",
        "eliminates",
        "rates",
        "scores",
        "educates",
        "serves",
        "measures",
        "reduces",
        "improves",
        "generates",
        "designs",
        "tracks",
        "verifies",
        "automates",
        "consults",
        "repairs",
        "detects",
        "buys",
        "sells",
        "monitors"
        ]

objects = [
        "developers",
        "managers",
        "spreadsheets",
        "marketing-triggers",
        "energy",
        "heating",
        "resources",
        "cars",
        "mobile phones",
        "bank accounts",
        "domains",
        "plattforms",
        "servers",
        "recommendations",
        "bookings",
        "alerts",
        "ratings",
        "content",
        "infrastructure",
        "KPIs",
        "risks",
        "robots",
        "source code",
        "acceptance",
        "usage",
        "health information",
        "loans",
        "authenticity",
        "luxury estates",
        "luxury goods",
        "rare items",
        "accomodation",
        "transport",
        "vitamins",
        "stocks",
        "remote-work",
        "vacations",
        "habits",
        "photos",
        "thermostats",
        "smartphones",
        "recruiting",
        "financial services",
        "shopping",
        "repairs",
        "fundraising",
        "customer service",
        "data",
        "documents",
        "photos",
        "medical procedures",
        "expenses",
        "campaigns"
        ]

technologies = [
        "AI",
        "IoT",
        "Blockchain",
        "NLP",
        "Simulations",
        "Adaptive Technology",
        "Agile development",
        "Big Data",
        "Business Intelligence",
        "Cloud Computing",
        "Crowd Sourcing",
        "Green technology",
        "Wearables",
        "Biometrics",
        "API",
        "The Internet",
        "Augmented Reality",
        "Computer Vision",
        "Middleware",
        "Gamification",
        "Custom Electronics",
        "3D Printing",
        "CI/CD",
        "Distributed Systems",
        "Service",
        "Datadriven Customer-Support",
        "Text-To-Speech",
        "OCR",
        "Smartphones",
        "GPS data",
        "Digital Diary",
        "Live Feed",
        "Scoring system",
        "Cellular network"
        ]

industries = [
    "Agriculture; plantations;other rural sectors",
    "Basic Metal Production",
    "Chemical industries",
    "Commerce",
    "Construction",
    "Education",
    "Financial services; professional services",
    "Food; drink; tobacco",
    "Forestry; wood; pulp and paper",
    "Health services",
    "Hotels; tourism; catering",
    "Mining (coal; other mining)", 
    "Mechanical and electrical engineering",
    "Media; culture; graphical",
    "Oil and gas production; oil refining",
    "Postal and telecommunications services",
    "Public service",
    "Shipping; ports; fisheries; inland waterways",
    "Textiles; clothing; leather; footwear",
    "Transport (including civil aviation; railways; road transport)",
    "Transport equipment manufacturing",
    "Utilities (water; gas; electricity)"
        ]
